### PR TITLE
F/support pester 5

### PR DESCRIPTION
**Pull request by Fiander**
#### Pull Request (PR) description

@johlju Two fixes for pester 3 #1550
#### This Pull Request (PR) fixes the following issues

- Fixes SqlRole
- Fixes SqlTraceFlag

#### Task list

- [ ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [X] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/johlju/sqlserverdsc/15)

### CODE REVIEW

**Comment by johlju** [comment]
Can you try to rebase the PR against my fork. In your local branch do:

```
git fetch origin f/support-pester-5
git rebase origin/f/support-pester-5
```

When everything looks okay. Make sure your changes (commit) to the tests are still there, run 

```
# This will overwrite the commits in the branch in your fork.
git push my --force
```

**Comment by Fiander** [comment]
Was already trying to do that, but your example made it a lot simpler.
i sometimes get really confused with all the git therms

**Review by johlju — CHANGES_REQUESTED** [review]
Thank you so much for helping in this effort! :smiley: 
 
I made some comments on the first test. We should rewrite the test to be optimized for Pester 5 (not just so they work). I think I need to write some guidance around this, I can put together a blog post on dsccommunity.org. 

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-:-MPclVGE3E3iDl4XDsEP:bkid4xr)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @Fiander)

___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 76 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPciP_I2pvNd9dckckE:-MPciP_I2pvNd9dckckF:bc0oxhu) ([raw file](https://github.com/johlju/sqlserverdsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L76)):*
> ```
>  -ErrorRecord $_
> ```

We should keep this as it will return the actual error as an inner exception. 

Also I suggest we don't change the code when we convert to Pester 5, it is a big enough change as it is. I suggest needed changes to code should be changed in the main repo first, then we rebase those changes into the Pester 5 working branch. :slightly_smiling_face: 
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 200 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcizSZ72QBFnEEdDOB:-MPcizSZ72QBFnEEdDOC:bjeowk0) ([raw file](https://github.com/johlju/sqlserverdsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L200)):*
> ```PowerShell
>                         -f $ServerName, $InstanceName, $ServerRoleName
> 
>                     New-InvalidOperationException -Message $errorMessage -ErrorRecord $_
> ```

Same as the previous comment.
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 227 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcj10C26mBNfTiZHPn:-MPcj10C26mBNfTiZHPo:b-cxfbnl) ([raw file](https://github.com/johlju/sqlserverdsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L227)):*
> ```PowerShell
>                             -f $ServerName, $InstanceName, $ServerRoleName
> 
>                         New-InvalidOperationException -Message $errorMessage -ErrorRecord $_
> ```

Same as previous comment.
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 534 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcj2EJD29lFjGkVrkP:-MPcj2EJD29lFjGkVrkQ:b-cxfbnl) ([raw file](https://github.com/johlju/sqlserverdsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L534)):*
> ```PowerShell
>             -f $ServerName, $InstanceName, $ServerRoleName, $SecurityPrincipal
> 
>         New-InvalidOperationException -Message $errorMessage -ErrorRecord $_
> ```

Same as previous comment.
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 589 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcj4sA6j52tUM6CsAw:-MPcj4sA6j52tUM6CsAx:b-cxfbnl) ([raw file](https://github.com/johlju/sqlserverdsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L589)):*
> ```PowerShell
>             -f $ServerName, $InstanceName, $ServerRoleName, $SecurityPrincipal
> 
>         New-InvalidOperationException -Message $errorMessage -ErrorRecord $_
> ```

Same as previous comment.
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 9 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcjMJNEmzZjau4xMT5:-MPcjMJNEmzZjau4xMT6:b-xia9mn) ([raw file](https://github.com/johlju/sqlserverdsc/blob/e01a609041134826da75e8ceca423074667d098d/tests/Unit/DSC_SqlRole.Tests.ps1#L9)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> if (-not (Test-BuildCategory -Type 'Unit'))
> {
>     return
> }
> ```
</details>


We can remove this, not needed with the new pipeline.
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 15 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcjUYf77WRQstf7vH_:-MPcjUYf77WRQstf7vHa:b-bpivof) ([raw file](https://github.com/johlju/sqlserverdsc/blob/e01a609041134826da75e8ceca423074667d098d/tests/Unit/DSC_SqlRole.Tests.ps1#L15)):*
<details><summary><i alt="summary">Quoted 23 lines of code…</i></summary>

> ```
> $script:dscModuleName = 'SqlServerDsc'
> $script:dscResourceName = 'DSC_SqlRole'
> function Invoke-TestSetup
> {
>     try
>     {
>         Import-Module -Name DscResource.Test -Force -ErrorAction 'Stop'
>     }
>     catch [System.IO.FileNotFoundException]
>     {
>         throw 'DscResource.Test module dependency not found. Please run ".\build.ps1 -Tasks build" first.'
>     }
>     $script:testEnvironment = Initialize-TestEnvironment `
>         -DSCModuleName $script:dscModuleName `
>         -DSCResourceName $script:dscResourceName `
>         -ResourceType 'Mof' `
>         -TestType 'Unit'
> }
> function Invoke-TestCleanup
> {
>     Restore-TestEnvironment -TestEnvironment $script:testEnvironment
> }
> Invoke-TestSetup
> ```
</details>


This should be replaced with 
https://github.com/johlju/SqlServerDsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/tests/Unit/DSC_SqlProtocol.Tests.ps1#L6-L40
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 42 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcjqPs56n9JccbAN6F:-MPcjqPs56n9JccbAN6G:b-2t8pjc) ([raw file](https://github.com/johlju/sqlserverdsc/blob/e01a609041134826da75e8ceca423074667d098d/tests/Unit/DSC_SqlRole.Tests.ps1#L42)):*
> ```
> try
> {
> ```

Try-finally-block should be removed.
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 44 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcju5vC9QhYhNdQ0eX:-MPcju5vC9QhYhNdQ0eY:b-svx5o1) ([raw file](https://github.com/johlju/sqlserverdsc/blob/e01a609041134826da75e8ceca423074667d098d/tests/Unit/DSC_SqlRole.Tests.ps1#L44)):*
> ```
> InModuleScope $script:dscResourceName {
> ```

`InModuleScope` should only be inside `Before*`-/`After*`-blocks and `It`-blocks. If they are not that code is run during discovery which we should avoid.

See this:

- BeforeAll-block that uses InModuleScope to set script variables in the module's scope (that will be used by it-blocks' InModuleScope): https://github.com/johlju/SqlServerDsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/tests/Unit/DSC_SqlProtocol.Tests.ps1#L43
- It-block that uses `InModuleScope`: https://github.com/johlju/SqlServerDsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/tests/Unit/DSC_SqlProtocol.Tests.ps1#L126
- It-block that uses `InModuleScope`with parameters: https://github.com/johlju/SqlServerDsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/tests/Unit/DSC_SqlProtocol.Tests.ps1#L169
- It-block that assert `Should -Invoke` (outside  `InModuleScope`): https://github.com/johlju/SqlServerDsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/tests/Unit/DSC_SqlProtocol.Tests.ps1#L290

**Review by Fiander — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/johlju/sqlserverdsc/15)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 76 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPciP_I2pvNd9dckckE:-MPcs-XA5CgIKZY6CZtz:blceq24) ([raw file](https://github.com/johlju/sqlserverdsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L76)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>  -ErrorRecord $_
> ```

We should keep this as it will return the actual error as an inner exception. 

Also I suggest we don't change the code when we convert to Pester 5, it is a big enough change as it is. I suggest needed changes to code should be changed in the main repo first, then we rebase those changes into the Pester 5 working branch. :slightly_smiling_face: 
</blockquote></details>

yea, i found that one too at a later module. 
there i "fixed" it by changing $mockErrorRecord.Exception.Message to "$($mockErrorRecord.Exception.Message)*"
in the test. that way it also works.
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 200 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcizSZ72QBFnEEdDOB:-MPcsLeq4TtZftGg4Y5S:bb7od0r) ([raw file](https://github.com/johlju/sqlserverdsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L200)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as the previous comment.
</blockquote></details>

same
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 227 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcj10C26mBNfTiZHPn:-MPcsNFu91BlOBzYfx3T:bb7od0r) ([raw file](https://github.com/johlju/sqlserverdsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L227)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as previous comment.
</blockquote></details>

same
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 534 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcj2EJD29lFjGkVrkP:-MPcsObFEJDYz_yApKi7:bb7od0r) ([raw file](https://github.com/johlju/sqlserverdsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L534)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as previous comment.
</blockquote></details>

same
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 589 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcj4sA6j52tUM6CsAw:-MPcsPb-Cf_X_CcpVxmG:bb7od0r) ([raw file](https://github.com/johlju/sqlserverdsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L589)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as previous comment.
</blockquote></details>

same
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 44 at r2](https://reviewable.io/reviews/johlju/sqlserverdsc/15#-MPcju5vC9QhYhNdQ0eX:-MPd7FOXEPQHaFQM2o3V:bf29fnl) ([raw file](https://github.com/johlju/sqlserverdsc/blob/e01a609041134826da75e8ceca423074667d098d/tests/Unit/DSC_SqlRole.Tests.ps1#L44)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> InModuleScope $script:dscResourceName {
> ```

`InModuleScope` should only be inside `Before*`-/`After*`-blocks and `It`-blocks. If they are not that code is run during discovery which we should avoid.

See this:

- BeforeAll-block that uses InModuleScope to set script variables in the module's scope (that will be used by it-blocks' InModuleScope): https://github.com/johlju/SqlServerDsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/tests/Unit/DSC_SqlProtocol.Tests.ps1#L43
- It-block that uses `InModuleScope`: https://github.com/johlju/SqlServerDsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/tests/Unit/DSC_SqlProtocol.Tests.ps1#L126
- It-block that uses `InModuleScope`with parameters: https://github.com/johlju/SqlServerDsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/tests/Unit/DSC_SqlProtocol.Tests.ps1#L169
- It-block that assert `Should -Invoke` (outside  `InModuleScope`): https://github.com/johlju/SqlServerDsc/blob/a7d8e4462e27e4808bb484aecf3ad78a4ceb0b3c/tests/Unit/DSC_SqlProtocol.Tests.ps1#L290
</blockquote></details>

working on it, just to let you know. And yes, a simple example would be appreciated.

**Comment by johlju** [comment]
Appreciate your help! 😃  I'm working on a blog post. I think I can push a draft later today. I will link to it then. 🙂

**Comment by johlju** [comment]
First draft. Didn't come as far as I hoped, but continue tomorrow. Hopefully it is to some help: https://github.com/dsccommunity/dsccommunity.org/blob/98c4e19b5356e6b3afccb488c3f90f10f90d01db/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md

**Comment by johlju** [comment]
Almost done, new draft here as the URL changes for each push: https://github.com/dsccommunity/dsccommunity.org/blob/75a808da985c3784358c521525d9e88d443f66d6/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md

**Comment by johlju** [comment]
Now the blog is posted https://dsccommunity.org/blog/convert-tests-to-pester5-for-dsc-community-repository/

**Comment by johlju** [comment]
I'm closing this as they have now been converted in the PR https://github.com/dsccommunity/SqlServerDsc/pull/1550.

**Pull request closed without merging**
